let celsius = 30;
let fahrenheit = (celsius * 9/5) + 32;
console.log("Температура у Фаренгейтах: ", fahrenheit);
let daysInMonth = 31;
let hoursInMonth = daysInMonth * 24;
let minutesInMonth = hoursInMonth * 60;
console.log("Годин у місяці: ", hoursInMonth);
console.log("Хвилин у місяці: ", minutesInMonth);
let health = 90;
let energy = 70;
health -= 15;
energy -= 20;
console.log("Рівень здоров'я: ", health);
console.log("Рівень енергії: ", energy);
let totalPrice = 150;
let discount = 0.15;
let discountedPrice = totalPrice * (1 - discount);
console.log("Ціна зі знижкою: ", discountedPrice);
const floatNumber = 18.92;
let roundedDown = Math.floor(floatNumber);
console.log("Округлене число: ", roundedDown);
const floatString = "67.89";
let parsedFloat = parseFloat(floatString);
console.log("Перетворене число (float): ", parsedFloat);
const intString = "987";
let parsedInt = parseInt(intString);
console.log("Перетворене число (int): ", parsedInt);
let number = 64;
let sqrtNumber = Math.sqrt(number);
console.log("Квадратний корінь числа: ", sqrtNumber);
const integer = 55;
const stringNumber = "444";
let convertedInt = parseInt(stringNumber);
let convertedString = integer.toString();
console.log("Перетворене число: ", convertedInt);
console.log("Перетворене у рядок: ", convertedString);